export const hosp =
  [{ "nomeVul": "Abacate(Persea gratissima)", "nomeSci": "Persea gratissima" },
 { "nomeVul": "Abeto Europeu", "nomeSci": "Picea abies" },
 { "nomeVul": "Abeto Vermelho Comum", "nomeSci": "Picea abies" },
 { "nomeVul": "Abiu", "nomeSci": "Chrysophyllum cainito" },
 { "nomeVul": "Acerola", "nomeSci": "Malpighia punicifolia" },
 { "nomeVul": "Acerola(qualquer espécie)", "nomeSci": "Malpighia spp." },
 { "nomeVul": "Acácia", "nomeSci": "Acacia sp." },
 { "nomeVul": "Albízia", "nomeSci": "Albizia lebbeck" },
 { "nomeVul": "Alder", "nomeSci": "Alnus sp." },
 { "nomeVul": "Alder Cinza", "nomeSci": "Alnus incana" },
 { "nomeVul": "Alder Japonês", "nomeSci": "Alnus japonica" },
 { "nomeVul": "Alder Negro", "nomeSci": "Alnus glutinosa" },
 { "nomeVul": "Alder Vermelha", "nomeSci": "Alnus rubra" },
 { "nomeVul": "Algodão Americano", "nomeSci": "Populus wislizeni" },
 { "nomeVul": "Ameixa", "nomeSci": "Prunus spp." },
 { "nomeVul": "Ameixeira - japonesa", "nomeSci": "Prunus salicina" },
 { "nomeVul": "Amelanchier", "nomeSci": "Amelanchier laevis" },
 { "nomeVul": "Amendoeira", "nomeSci": "Terminalia catappa" },
 { "nomeVul": "Amieiro", "nomeSci": "Alnus glutinosa" },
 { "nomeVul": "Amieiro Negro", "nomeSci": "Frangula almus" },
 { "nomeVul": "Angico", "nomeSci": "Acacia sp." },
 { "nomeVul": "Arapaju", "nomeSci": "Manilkara zapota" },
 { "nomeVul": "Arbusto Espinheiro do Bosque", "nomeSci": "Crataegus oxyacanthoides(syn: oxyacantha)" },
 { "nomeVul": "Arbusto Espinhento", "nomeSci": "Craetaegus monogyna" },
 { "nomeVul": "Aveia", "nomeSci": "Avena sativa" },
 { "nomeVul": "Aveleira Japonesa", "nomeSci": "Corylus sieboldiana" },
 { "nomeVul": "Aveleira Siberiana", "nomeSci": "Corylus heterophylla var.thunbergiii" },
 { "nomeVul": "Avelã", "nomeSci": "Corylus avellana" },
 { "nomeVul": "Azevinho", "nomeSci": "Ilex aquifolium" },
 { "nomeVul": "Bacupari", "nomeSci": "Garcinia dulcis" },
 { "nomeVul": "Banana", "nomeSci": "Musa spp." },
 { "nomeVul": "Bergamota", "nomeSci": "Citrus reticulata" },
 { "nomeVul": "Bilimbi", "nomeSci": "Chrysophyllum cainito" },
 { "nomeVul": "Bordo", "nomeSci": "Acer sp." },
 { "nomeVul": "Bordo(A.mono)", "nomeSci": "Acer mono subsp.Heterophyllum" },
 { "nomeVul": "Bordo(A.negundo)", "nomeSci": "Acer negundo" },
 { "nomeVul": "Bordo(A.sacharum)", "nomeSci": "Acer saccharum" },
 { "nomeVul": "Bordo(A.spicatum)", "nomeSci": "Acer spicatum" },
 { "nomeVul": "Bordo(Acer pennsylvanicum)", "nomeSci": "Acer pennsylvanicum" },
 { "nomeVul": "Bordo(Acer pseudoplatanus)", "nomeSci": "Acer pseudoplatanus" },
 { "nomeVul": "Bordo Japonês", "nomeSci": "Acer palmatum" },
 { "nomeVul": "Bordo Vermelho(A.macrophyllum)", "nomeSci": "Acer macrophyllum" },
 { "nomeVul": "Bordo Vermelho(A.rubrum)", "nomeSci": "Acer rubrum" },
 { "nomeVul": "Bordo-da-videira", "nomeSci": "Acer circinatum" },
 { "nomeVul": "Broto Vermelho Oriental", "nomeSci": "Cercis canadensis" },
 { "nomeVul": "Bálsamo", "nomeSci": "Myroxylon balsamum" },
 { "nomeVul": "Bétula", "nomeSci": "Betula sp." },
 { "nomeVul": "Bétula Branca(B.papyrifera)", "nomeSci": "Betula papyrifera" },
 { "nomeVul": "Bétula Branca(B.pubescens)", "nomeSci": "Betula pubescens" },
 { "nomeVul": "Bétula Branca(B.pendula)", "nomeSci": "Betula pendula (syn:verrucosa)"},
 { "nomeVul": "Bétula Cinza", "nomeSci": "Betula populifolia" },
 { "nomeVul": "Bétula Lenta", "nomeSci": "Betula lenta" },
 { "nomeVul": "Bétula lenta", "nomeSci": "Betula nigra" },
 { "nomeVul": "Bétula Lutea", "nomeSci": "Betula lutea(synonym: alleghaniensis)" },
 { "nomeVul": "Bétula Monarca", "nomeSci": "Betula maximowicziana" },
 { "nomeVul": "Bétula Negra", "nomeSci": "Betula nigra" },
 { "nomeVul": "Bétula Papel", "nomeSci": "Betula papyrifera" },
 { "nomeVul": "Cabeça - de - negro", "nomeSci": "Albizia lebbeck" },
 { "nomeVul": "Caimito", "nomeSci": "Chrysophyllum cainito" },
 { "nomeVul": "Cajazeiro", "nomeSci": "Spondias lutea" },
 { "nomeVul": "Caju", "nomeSci": "Anacardium occidentale" },
 { "nomeVul": "Carambola", "nomeSci": "Averrhoa carambola" },
 { "nomeVul": "Carambola amarela", "nomeSci": "Chrysophyllum cainito" },
 { "nomeVul": "Carvalho", "nomeSci": "Quercus sp." },
 { "nomeVul": "Carvalho Branco", "nomeSci": "Quercus alba" },
 { "nomeVul": "Carvalho Branco do Brejo", "nomeSci": "Quercus bicolor" },
 { "nomeVul": "Carvalho Branco Oregon", "nomeSci": "Quercus garryana" },
 { "nomeVul": "Carvalho Campeão(Q.borealis)", "nomeSci": "Quercus borealis(syn: rubra)" },
 { "nomeVul": "Carvalho Campeão(Q.rubra)", "nomeSci": "Quercus rubra" },
 { "nomeVul": "Carvalho Castanheiro", "nomeSci": "Quercus montana" },
 { "nomeVul": "Carvalho Escarlata", "nomeSci": "Quercus coccinea" },
 { "nomeVul": "Carvalho Folha Diamante", "nomeSci": "Quercus laurifolia" },
 { "nomeVul": "Carvalho Glorioso", "nomeSci": "Quercus laurifolia" },
 { "nomeVul": "Carvalho Glorioso do Brejo", "nomeSci": "Quercus laurifolia" },
 { "nomeVul": "Carvalho Konara", "nomeSci": "Quercus glandulifera" },
 { "nomeVul": "Carvalho Koreano", "nomeSci": "Quercus glandulifera" },
 { "nomeVul": "Carvalho Mongoliano", "nomeSci": "Quercus mongolica var grosserrata" },
 { "nomeVul": "Carvalho Obtuso", "nomeSci": "Quercus laurifolia" },
 { "nomeVul": "Carvalho Oregon", "nomeSci": "Quercus garryana" },
 { "nomeVul": "Carvalho Preto", "nomeSci": "Quercus velutina" },
 { "nomeVul": "Carvalho Vermelho do Norte(Q.borealis)", "nomeSci": "Quercus borealis(syn: rubra)" },
 { "nomeVul": "Carvalho Vermelho do Norte(Q.rubra)", "nomeSci": "Quercus rubra" },
 { "nomeVul": "Carvalho Água", "nomeSci": "Quercus laurifolia" },
 { "nomeVul": "Carvalho - alvarinho", "nomeSci": "Quercus robur" },
 { "nomeVul": "Carvalho - roble", "nomeSci": "Quercus robur" },
 { "nomeVul": "Carvalho - vermelho", "nomeSci": "Quercus robur" },
 { "nomeVul": "Castanha - da - Índia", "nomeSci": "Aesculus sp." },
 { "nomeVul": "Castanha - da - Índia(A.hippocastanum)", "nomeSci": "Aesculus hippocastanum" },
 { "nomeVul": "Castanheiro Europeu", "nomeSci": "Castanea dentata" },
 { "nomeVul": "Cereja de Pássaro", "nomeSci": "Prunus ssiori" },
 { "nomeVul": "Cereja de Pássaro Virginia", "nomeSci": "Prunus virginiana" },
 { "nomeVul": "Cerejeira", "nomeSci": "Prunus avium" },
 { "nomeVul": "Cerejeira Chorona", "nomeSci": "Prunus subhirtella var.pendula" },
 { "nomeVul": "Cerejeira Negra", "nomeSci": "Prunus serotina" },
 { "nomeVul": "Choupo", "nomeSci": "Populus spp." },
 { "nomeVul": "Choupo(P.x canadensis)", "nomeSci": "Populus x canadensis" },
 { "nomeVul": "Choupo Branco", "nomeSci": "Populus alba" },
 { "nomeVul": "Choupo Tremedor", "nomeSci": "Populus tremula" },
 { "nomeVul": "Choupo Trêmulo", "nomeSci": "Populus tremuloides" },
 { "nomeVul": "Choupo - bálsamo", "nomeSci": "Populus balsamifera" },
 { "nomeVul": "Chuva - de - ouro", "nomeSci": "Laburnum anagyrioides" },
 { "nomeVul": "Chá - da - Índia", "nomeSci": "Camellia sinensis" },
 { "nomeVul": "Cinamomo", "nomeSci": "Melia azedarach" },
 { "nomeVul": "Cinza Japonês", "nomeSci": "Fraxinus mandshurica var.Japonica" },
 { "nomeVul": "Cinza - da - montanha", "nomeSci": "Sorbus sp." },
 { "nomeVul": "Citros", "nomeSci": "Citrus spp." },
 { "nomeVul": "Coprosma Frondoso Fino", "nomeSci": "Coprosma areolata" },
 { "nomeVul": "Coqueiro", "nomeSci": "Cocos nucifera" },
 { "nomeVul": "Corrente - de - ouro", "nomeSci": "Laburnum anagyrioides" },
 { "nomeVul": "Cárpino", "nomeSci": "Carpinus sp." },
 { "nomeVul": "Cárpino Betulas", "nomeSci": "Carpinus betulas" },
 { "nomeVul": "Espinho Branco", "nomeSci": "Craetaegus monogyna" },
 { "nomeVul": "Faia", "nomeSci": "Fagus sp." },
 { "nomeVul": "Faia Americana", "nomeSci": "Fagus americana" },
 { "nomeVul": "Faia Cobre", "nomeSci": "Fagus sylvantica" },
 { "nomeVul": "Faia do Oriente", "nomeSci": "Fagus orientalis" },
 { "nomeVul": "Faia Japonesa", "nomeSci": "Fagus crenata f.grandifolia(syn.Americana)" },
 { "nomeVul": "Faia Roxa", "nomeSci": "Fagus silvatica f.purpurea" },
 { "nomeVul": "Falso Castanho Japonês", "nomeSci": "Aesculus turbinata" },
 { "nomeVul": "Faveiro", "nomeSci": "Albizia lebbeck" },
 { "nomeVul": "Feixe Branco", "nomeSci": "Sorbus aria" },
 { "nomeVul": "Flamboyant", "nomeSci": "Delonix regia" },
 { "nomeVul": "Fortunela", "nomeSci": "Fortunella spp." },
 { "nomeVul": "Freixo(F.bungeana)", "nomeSci": "Fraxinus bungeana" },
 { "nomeVul": "Freixo(F.excelsior)", "nomeSci": "Fraxinus excelsior" },
 { "nomeVul": "Fruta Pão", "nomeSci": "Artocarpus altilis" },
 { "nomeVul": "Gafanhoto Preto", "nomeSci": "Robinia pseudoacacia" },
 { "nomeVul": "Goiaba", "nomeSci": "Psidium guajava" },
 { "nomeVul": "Goma Preta", "nomeSci": "Nyssa sylvatica" },
 { "nomeVul": "Gomuto", "nomeSci": "Arenga pinnata" },
 { "nomeVul": "Grão Amargo", "nomeSci": "Prunus virginiana" },
 { "nomeVul": "Helicônia", "nomeSci": "Heliconia spp." },
 { "nomeVul": "Jaca", "nomeSci": "Artocarpus integrifolia" },
 { "nomeVul": "Jambo Branco(S.aqueum)", "nomeSci": "Syzygium aqueum" },
 { "nomeVul": "Jambo Branco(S.samarangense)", "nomeSci": "Syzygium samarangense" },
 { "nomeVul": "Jambo D'água", "nomeSci": "Syzygium aqueum" },
 { "nomeVul": "Jambo Rosa", "nomeSci": "Syzygium jambos" },
 { "nomeVul": "Jambo Vermelho", "nomeSci": "Syzygium malaccense" },
 { "nomeVul": "Juglans", "nomeSci": "Juglans sp." },
 { "nomeVul": "Jujuba (Z. jujuba)", "nomeSci": "Ziziphus jujuba" },
 { "nomeVul": "Jujuba (Z. mauritiana)", "nomeSci": "Ziziphus mauritiana" },
 { "nomeVul": "Jurema", "nomeSci": "Acacia sp." },
 { "nomeVul": "Karamu", "nomeSci": "Coprosma lucida" },
 { "nomeVul": "Kowhai", "nomeSci": "Sophora microphylla" },
 { "nomeVul": "Laranja", "nomeSci": "Citrus sinensis" },
 { "nomeVul": "Laranja Azeda", "nomeSci": "Citrus aurantium" },
 { "nomeVul": "Limão Cayena", "nomeSci": "Averrhoa bilimbi" },
 { "nomeVul": "Linda-dos-jardins", "nomeSci": "Rhus typhina" },
 { "nomeVul": "Louro Califórnia", "nomeSci": "Umbelluraria californica" },
 { "nomeVul": "Manchu Cinza", "nomeSci": "Fraxinus mandshurica" },
 { "nomeVul": "Mandioca", "nomeSci": "Manihot esculenta" },
 { "nomeVul": "Manga", "nomeSci": "Mangifera indica" },
 { "nomeVul": "Mararaju", "nomeSci": "Manilkara zapota" },
 { "nomeVul": "Maça", "nomeSci": "Malus sp." },
 { "nomeVul": "Maçaranduba", "nomeSci": "Manilkara zapota" },
 { "nomeVul": "Maçã (M. communis)", "nomeSci": "Malus communis" },
 { "nomeVul": "Maçã (M. pumila var domestica)", "nomeSci": "Malus pumila var domestica" },
 { "nomeVul": "Maçã (M. pumila)", "nomeSci": "Malus pumila" },
 { "nomeVul": "Maçã (M. x domestica)", "nomeSci": "Malus x domestica" },
 { "nomeVul": "Maçã (Pyrus malus)", "nomeSci": "Pyrus malus" },
 { "nomeVul": "Maçã Silvestre", "nomeSci": "Malus sylvestris" },
 { "nomeVul": "Mexerica", "nomeSci": "Citrus reticulata" },
 { "nomeVul": "Mogno", "nomeSci": "Switenia macrophyla" },
 { "nomeVul": "Mogno Indiano Ocidental", "nomeSci": "Swietenia mahagoni" },
 { "nomeVul": "Murta", "nomeSci": "Murraya paniculata" },
 { "nomeVul": "Nespereira", "nomeSci": "Eriobotrya japonica" },
 { "nomeVul": "Nim", "nomeSci": "Azadirachta indica" },
 { "nomeVul": "Nogueira", "nomeSci": "Juglans sp." },
 { "nomeVul": "Nogueira Amarga", "nomeSci": "Carya cordiformis" },
 { "nomeVul": "Nogueira Amarga", "nomeSci": "Carya spp." },
 { "nomeVul": "Nogueira Amarga Casca de Pelúcia", "nomeSci": "Carya ovata" },
 { "nomeVul": "Nogueira Amarga Coração Branco", "nomeSci": "Carya tomentosa" },
 { "nomeVul": "Nogueira Amarga de Porco", "nomeSci": "Carya glabra" },
 { "nomeVul": "Nogueira Branca", "nomeSci": "Juglans cinerea" },
 { "nomeVul": "Nogueira Comum", "nomeSci": "Juglans regia" },
 { "nomeVul": "Nogueira europeia", "nomeSci": "Juglans regia" },
 { "nomeVul": "Nogueira Pecã", "nomeSci": "Carya illinoensis" },
 { "nomeVul": "Nogueira Preta", "nomeSci": "Juglans nigra" },
 { "nomeVul": "Noruega Abeto", "nomeSci": "Picea abies" },
 { "nomeVul": "Olmo", "nomeSci": "Ulmus sp." },
 { "nomeVul": "Olmo Americano", "nomeSci": "Ulmus americana" },
 { "nomeVul": "Olmo Escocês", "nomeSci": "Ulmus glabra (syn. montana)" },
 { "nomeVul": "Padreiro", "nomeSci": "Acer pseudoplatanus" },
 { "nomeVul": "Palma forrageira", "nomeSci": "Opuntia cochenillifera" },
 { "nomeVul": "Pau Cachorro", "nomeSci": "Cornus sp." },
 { "nomeVul": "Pau Cachorro do Pacífico", "nomeSci": "Cornus muttallii" },
 { "nomeVul": "Pera Asiática", "nomeSci": "Pyrus pyrifolia" },
 { "nomeVul": "Pera Nashi", "nomeSci": "Pyrus pyrifolia" },
 { "nomeVul": "Pereira Europeia", "nomeSci": "Pyrus communis" },
 { "nomeVul": "Pereira Japonesa", "nomeSci": "Pyrus pyrifolia var culta" },
 { "nomeVul": "Pimenta Picante", "nomeSci": "Capsicum annuum" },
 { "nomeVul": "Pimenta-do-diabo", "nomeSci": "Capsicum annuum" },
 { "nomeVul": "Pitanga Vermelha", "nomeSci": "Eugenia uniflora" },
 { "nomeVul": "Plátano", "nomeSci": "Platanus orientalis" },
 { "nomeVul": "Plátano Oriental", "nomeSci": "Platanus orientalis" },
 { "nomeVul": "Pomelo", "nomeSci": "Citrus paradisi" },
 { "nomeVul": "Poncirus", "nomeSci": "Poncirus spp." },
 { "nomeVul": "Ponkan", "nomeSci": "Citrus reticulata" },
 { "nomeVul": "Ribes", "nomeSci": "Ribes sp." },
 { "nomeVul": "Rosa", "nomeSci": "Rosa spp." },
 { "nomeVul": "Rustifina Rus", "nomeSci": "Rhus typhina" },
 { "nomeVul": "Salgueiro Branco", "nomeSci": "Salix alba" },
 { "nomeVul": "Salgueiro Cinza", "nomeSci": "Salix cinerea" },
 { "nomeVul": "Salgueiro Dourado", "nomeSci": "Salix alba var Vitelina" },
 { "nomeVul": "Salgueiro Preto", "nomeSci": "Salix nigricans" },
 { "nomeVul": "Salgueiro Púrpura", "nomeSci": "Salix purpurea" },
 { "nomeVul": "Salgueiro Velho Mundo", "nomeSci": "Salix amygdalina" },
 { "nomeVul": "Salgueiro-folha-de-pêssego", "nomeSci": "Salix amygdaloides" },
 { "nomeVul": "Salgueiro-taco-de-críquete", "nomeSci": "Salix alba L. Coerulea" },
 { "nomeVul": "Salix", "nomeSci": "Salix spp." },
 { "nomeVul": "Sanguinho", "nomeSci": "Frangula almus" },
 { "nomeVul": "Sapoti", "nomeSci": "Manilkara zapota" },
 { "nomeVul": "Seringueira", "nomeSci": "Hevea brasiliensis" },
 { "nomeVul": "Sete Copas", "nomeSci": "Terminalia catappa" },
 { "nomeVul": "Sorgo", "nomeSci": "Sorghum bicolor" },
 { "nomeVul": "Sorva", "nomeSci": "Sorbus sp." },
 { "nomeVul": "Sorva (S. domestica)", "nomeSci": "Sorbus domestica" },
 { "nomeVul": "Sumac Staghorn", "nomeSci": "Rhus typhina" },
 { "nomeVul": "Sófora", "nomeSci": "Sophora microphylla" },
 { "nomeVul": "Tangerina", "nomeSci": "Citrus reticulata" },
 { "nomeVul": "Taperebá", "nomeSci": "Spondias lutea" },
 { "nomeVul": "Teca", "nomeSci": "Tectona grandis" },
 { "nomeVul": "Teja", "nomeSci": "Tilia cordata" },
 { "nomeVul": "Tejo", "nomeSci": "Tilia cordata" },
 { "nomeVul": "Tella", "nomeSci": "Tilia cordata" },
 { "nomeVul": "Texa", "nomeSci": "Tilia cordata" },
 { "nomeVul": "Tilha", "nomeSci": "Tilia cordata" },
 { "nomeVul": "Tillera", "nomeSci": "Tilia cordata" },
 { "nomeVul": "Tilo", "nomeSci": "Tilia americana" },
 { "nomeVul": "Tomate", "nomeSci": "Licopersicum esculentum" },
 { "nomeVul": "Toranja", "nomeSci": "Citrus paradisi" },
 { "nomeVul": "Tramazeira", "nomeSci": "Sorbus aucuparia" },
 { "nomeVul": "Tulipeiro", "nomeSci": "Liriodendron tulipifera" },
 { "nomeVul": "Tupelo", "nomeSci": "Nyssa sylvatica" },
 { "nomeVul": "Tília", "nomeSci": "Tilia sp." },
 { "nomeVul": "Ulmeiro", "nomeSci": "Ulmus sp." },
 { "nomeVul": "Unha-de-gato", "nomeSci": "Acacia sp." },
 { "nomeVul": "Videira e seus híbridos", "nomeSci": "Vitis spp. e seus híbridos" },
 { "nomeVul": "Vimeiro Púrpura", "nomeSci": "Salix purpurea" },
 { "nomeVul": "Viola", "nomeSci": "Viola sp." },
 { "nomeVul": "Álamo", "nomeSci": "Populus spp." },
 { "nomeVul": "Álamo (Populus x canadensis)", "nomeSci": "Populus x canadensis" },
 { "nomeVul": "Álamo Americano", "nomeSci": "Tilia americana" },
 { "nomeVul": "Álamo Branco", "nomeSci": "Populus alba" },
 { "nomeVul": "Álamo Grande Dente", "nomeSci": "Populus grandidenta" },
 { "nomeVul": "Árvore Preta", "nomeSci": "Fraxinus nigra (syn. sambucifolia)" }]
